//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CheckTD.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CheckTD.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkMarkAttention {
            get {
                object obj = ResourceManager.GetObject("checkMarkAttention", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkMarkBad {
            get {
                object obj = ResourceManager.GetObject("checkMarkBad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap checkMarkGood_picture {
            get {
                object obj = ResourceManager.GetObject("checkMarkGood_picture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 300610
        ///3006400000
        ///3006700000
        ///3815199000
        ///4416000000
        ///680422
        ///7017
        ///730900
        ///730423000
        ///7310100000
        ///731100
        ///8205
        ///8207
        ///8208
        ///820900
        ///8401
        ///8402
        ///8403
        ///8404
        ///8405
        ///8406
        ///8407
        ///8408
        ///8409
        ///8410
        ///8411
        ///8412
        ///8413
        ///8414
        ///8415
        ///8416
        ///8417
        ///8418
        ///8419
        ///8420
        ///8421
        ///8422
        ///8423
        ///8424
        ///8425
        ///8426
        ///8427
        ///8428
        ///8429
        ///8430
        ///8431
        ///8432
        ///8433
        ///8434
        ///8435
        ///8436
        ///8437
        ///8438
        ///8439
        ///8440
        ///8441
        ///8442
        ///8443
        ///844400
        ///8445
        ///8446
        ///8447
        ///8448
        ///8449000000
        ///8450
        ///8451
        ///8452
        ///8453
        ///8454
        ///8455
        ///8456
        ///8457
        ///8458
        ///8459
        ///8460
        ///8461
        ///846 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cods311 {
            get {
                return ResourceManager.GetString("cods311", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 4416000000
        ///730900
        ///7310100000
        ///8421110000
        ///8421220000
        ///8422200009
        ///8422300008
        ///8427
        ///8428907100
        ///8428907800
        ///8432
        ///8433
        ///8434
        ///8435
        ///8436
        ///8437
        ///8438
        ///847420000
        ///8514191000
        ///8701
        ///9027500000
        ///
        ///8208
        ///840890
        ///8409100000
        ///8411
        ///8412
        ///880100
        ///8802
        ///8804000000
        ///8805
        ///8806
        ///8807100000
        ///8807200000
        ///8807300000
        ///8901
        ///890200
        ///8903
        ///890400
        ///8905
        ///8906
        ///8907
        ///8908000000
        ///
        ///3815199000
        ///680422
        ///731100
        ///7017
        ///8205
        ///8207
        ///820900
        ///8401
        ///8402
        ///8403
        ///8404
        ///8405
        ///8406
        ///8407
        ///8408
        ///8409
        ///8410
        ///8411
        ///8412
        ///8413
        ///8414
        ///8415
        ///8 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string cods312 {
            get {
                return ResourceManager.GetString("cods312", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 440121
        ///440122
        ///4403
        ///4408.
        /// </summary>
        internal static string cods313 {
            get {
                return ResourceManager.GetString("cods313", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 820559
        ///820719
        ///840510000
        ///841229
        ///841940000
        ///8421110000
        ///842121000
        ///8421220000
        ///842129000
        ///8422200009
        ///8421300008
        ///8428907100
        ///8428907800
        ///8430100000
        ///8430310000
        ///8430390000
        ///843041000
        ///843049000
        ///847410000
        ///847420000
        ///8474310000
        ///847432000
        ///847439000
        ///8807100000
        ///8807200000
        ///8807300000
        ///9027500000
        ///8514191000.
        /// </summary>
        internal static string codsExcluded312 {
            get {
                return ResourceManager.GetString("codsExcluded312", resourceCulture);
            }
        }
    }
}
